### ISSUE TITLE
Many discrepancies with Revert to Blue

### ISSUE THREAD

**Issue by MohsinTeddy** [STForScratch/ScratchTools#556]
### Describe the bug. What is going wrong?

A bunch of Issues with Revert to Blue
1. Profile header color is different to the main page header color and 404 oage
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/ae85c867-bc08-4824-99d4-f0449e961a4e)
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/5cae1452-77fd-41f4-9556-9554624cfc99)
2. Purple Text (Scratch Addons Dark mode)
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/bc1b6fb1-aafe-4af2-b346-a6587e91d07f)
3. Purple Profile Dropdown menu (Scratch Addons Dark mode)
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/ce9b0d32-67de-44a1-999b-13be9fb1ccb3)
4. Purple Griffpatch 😭
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/04cea800-5bea-48c3-8baf-45e96de3fd0d)
5. Purple Buttons (Scratch Addons Dark Mode)
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/ba42fdd8-02a3-4861-a7d4-48a297cb5670)
6. Purple Flag Highlight
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/713afc5b-257b-48ea-b471-91fe02a0928d)
7. Purple Sprite Highlight
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/b7975536-9cd0-4a13-aeea-7d46e09e0033)
8. Purple Comment Highlight
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/08fa0999-4a4a-43ca-8850-e0663117eeaa)
9. Purple Project Icon
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/ce9c5ec0-0226-47cc-aa9e-88bc7c659ef4)
10. Purple My Stuff Page
![image](https://github.com/STForScratch/ScratchTools/assets/97502836/a6fdaed2-5430-4be8-b2dc-672603c2b26a)

### What is causing the bug?

idk, not coded ig

**Comment by MaterArc** [comment]
> ### Describe the bug. What is going wrong?
> A bunch of Issues with Revert to Blue
> 
> 1. Profile header color is different to the main page header color and 404 oage
>    ![image](https://user-images.githubusercontent.com/97502836/251393791-ae85c867-bc08-4824-99d4-f0449e961a4e.png)
>    ![image](https://user-images.githubusercontent.com/97502836/251405038-5cae1452-77fd-41f4-9556-9554624cfc99.png)
> 2. Purple Text (Scratch Addons Dark mode)
>    ![image](https://user-images.githubusercontent.com/97502836/251394186-bc1b6fb1-aafe-4af2-b346-a6587e91d07f.png)
> 3. Purple Profile Dropdown menu (Scratch Addons Dark mode)
>    ![image](https://user-images.githubusercontent.com/97502836/251394751-ce9b0d32-67de-44a1-999b-13be9fb1ccb3.png)
> 4. Purple Griffpatch 😭
>    ![image](https://user-images.githubusercontent.com/97502836/251396885-04cea800-5bea-48c3-8baf-45e96de3fd0d.png)
> 5. Purple Buttons (Scratch Addons Dark Mode)
>    ![image](https://user-images.githubusercontent.com/97502836/251397230-ba42fdd8-02a3-4861-a7d4-48a297cb5670.png)
> 6. Purple Flag Highlight
>    ![image](https://user-images.githubusercontent.com/97502836/251404124-713afc5b-257b-48ea-b471-91fe02a0928d.png)
> 7. Purple Sprite Highlight
>    ![image](https://user-images.githubusercontent.com/97502836/251404503-b7975536-9cd0-4a13-aeea-7d46e09e0033.png)
> 8. Purple Comment Highlight
>    ![image](https://user-images.githubusercontent.com/97502836/251405662-08fa0999-4a4a-43ca-8850-e0663117eeaa.png)
> 9. Purple Project Icon
>    ![image](https://user-images.githubusercontent.com/97502836/251406025-ce9c5ec0-0226-47cc-aa9e-88bc7c659ef4.png)
> 10. Purple My Stuff Page
>     ![image](https://user-images.githubusercontent.com/97502836/251406311-a6fdaed2-5430-4be8-b2dc-672603c2b26a.png)
> 
> ### What is causing the bug?
> idk, not coded ig
> 
> ### Anything else?
> _No response_

Firstly, to address the first point, profile pages and 404 pages are 2.0 pages and the colors by default are darker than normal scratch blue and that's why we recreated it like that. Also, to address the second point, by default the scratch addons dark mode was recently updated making all links, highlight colors and more to be purple. That's why the front page links like griffpatch's username are purple. Also, I want to point out that griffpatch's icon being purple is not a bug from ScratchTools side, in fact it's not a bug from SA either. He changed his icon a few days ago to reflect the new scratch colors. The dropdown being that color is also a cause of the scratch addons dark mode addon. The purple buttons in the explore page - same thing, it's because of that addon. Purple sprite highlight is actually a bug, so thanks for that! Comment highlights too! I fixed the purple project icon color in a recent pr and it should be updated soon. The purple my stuff banner only exists because of SA and it's a result of the 2.0 to 3.0 addon. I can make a seperate pr addressing that concern. Thanks for the bug report :)

**Comment by medlans** [comment]
I wish it was compatible with SA's website color mode since I want certain things that SA doesn't add, but it causes other colors to be messed up and for the 3.0 pages to have the 3.0 colors instead of 2.0 ones, though that likely won't be added until later if at all.
Also, usernames in topics and closed topic links appear blue for me with this on.

**Comment by MaterArc** [comment]
> I wish it was compatible with SA's website color mode since I want certain things that SA doesn't add, but it causes other colors to be messed up and for the 3.0 pages to have the 3.0 colors instead of 2.0 ones, though that likely won't be added until later if at all. Also, usernames in topics and closed topic links appear blue for me with this on.

I'll try to add compatibility to this feature in the future, right now though, I want to make sure that the core aspects of the feature work and are for the most part bug-free.
